stages:
  - sync
  - build
  - test

default:
  tags:
    - third-runner
  image: alpine
  
sync_with_github:
  stage: sync
  script:
    - echo "Cloning GitHub repository..."
    - git clone https://github.com/alikhan-brac/gitTest.git
    - cd gitTest
    - echo "Pulling latest changes from GitHub..."
    - git pull origin main  # Change 'main' to your default branch
    - echo "Pushing changes to GitLab..."
    - git remote add gitlab https://gitlab.com/testgroup29313144/gitTest.git
    - git push https://<alikhan.brac>:${GITHUB_TOKEN}@gitlab.com/alikhan.brac/gitTest.git main
    # Change 'main' to your default branch
  only:
    - main  # Change to the branch you want to sync

create-file:
  stage: build
  script:
    - echo "started creating file"
    - mkdir -p b
    - echo "this is to test artifact" > b/testfile.txt
  artifacts:
    paths:
      - b/testfile.txt
    expire_in: 1 hour

test-file:
  stage: test
  dependencies:
    - create-file
  script:
    - echo "checking artifact"
    - test -f b/testfile.txt
    - cat b/testfile.txt
