stages:
    - build
    - test

default:
    tags:
        - gitlab-runner
    image: alpine

create-file:
    stage: build
    script:
        - echo "creating file"
        - echo "this a test file added to artifact" > art/art.txt
    artifact:
        - art/art.txt
        - expires : 1 hour
        
test-file:
    stage: test
    script: echo "checking file if exists"
    script: cat art/art.txt
