stages:
  - build
  - test

default:
  tags:
    - third-runner
  image: alpine

create-file:
  stage: build
  script:
    - echo "started creating file"
    - mkdir -p b
    - echo "this is to test artifact" > b/testfile.txt
  artifacts:
    paths:
      - b/testfile.txt
    expire_in: 1 hour

test-file:
  stage: test
  dependencies:
    - create-file
  script:
    - echo "checking artifact"
    - test -f b/testfile.txt
    - cat b/testfile.txt
